name: User Story
description: Define a user story
title: "[Story]: "
labels: ["story"]
assignees:
  - jjvilches
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to define this new user story
  - type: textarea
    id: what-needs
    attributes:
      label: What is your need?
      description: Describe us your needs from a user point of view
      placeholder: As a <user>, I want to be able to <functionality> so that <user objective>
      value: "Example: As a developer, I want to be able to measure the CPU runtime so that I can monitor if enough ressources are allocated to the process."
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: On which platform will the user story be implemented?
      options:
        - EBDL
        - ADAS Record 2.0
        - HIL Replay
        - Other
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Which priority has this story ?
      options:
        - Highest
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: input
    id: Due-Date
    attributes:
      label: When is the resolution due ?
      value: YYYY-mm-dd
  - type: dropdown
    id: effort-estimate
    attributes:
      label: Provide an effort estimate in T-Shirt size
      options:
        - XXS
        - XS
        - S
        - M
        - L
        - XL
  - type: textarea
    id: acknowledged
    attributes:
      label: Acknowledgement
      description: Team accepts the story and commits to implementation. Requirements needs to be refined
      placeholder: 
  - type: textarea
    id: defined
    attributes:
      label: Definition//Acceptance Criteria
      description: Requirements//Acceptance criterias have been gathered and are listed here
      placeholder: "- [] Functional Requirement 1 \n
      - [] Functional Requirement 2 \n
      -[] Non Functional Requirement 1 \n
      .
      .
      .
      "
  - type: textarea
    id: version
    attributes:
      label: Integration version
      description: Write down on which release/source code pull was the user story implemented
      placeholder: "Release 1.4 // #1236fdw45"
  - type: textarea
    id: test
    attributes:
      label: test
      description: Write down which requirements have not been met.
      placeholder: "Non functional requirement 1 was not fullfilled as the system was 3 seconds slower. \n
      Test ID xxxxxx \n
      Test Description xxxxxx"
